### ISSUE TITLE
mojo-executor 2.2.0 with maven 3.3.9

### ISSUE THREAD

**Issue by hiddusk** [TimMoore/mojo-executor#32]
Hi,

when we used mojo-executor 2.2.0 with maven 3.3.9 in one of our plugin and building app some app using this plugin getting below error: 

Unable to execute mojo: java.lang.reflect.InvocationTargetException: NullPointerException -> [Help 1]

Could you please update on this

Thanks,
Hidayath.

**Comment by hiddusk** [comment]
le to execute mojo
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
        at uk.co.igindex.maven.plugins.webbuild.MojoExecutor.executeLifecycleToPhase(MojoExecutor.java:97)
        at uk.co.igindex.maven.plugins.webbuild.BuildToWebappMojo.execute(BuildToWebappMojo.java:89)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:96)
        at uk.co.igindex.maven.plugins.webbuild.MojoExecutor.executeLifecycleToPhase(MojoExecutor.java:78)
        ... 23 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.twdata.maven.mojoexecutor.MavenCompatibilityHelper.loadPluginDescriptor(MavenCompatibilityHelper.java:78)
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:85)
        ... 24 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.twdata.maven.mojoexecutor.MavenCompatibilityHelper.loadPluginDescriptor(MavenCompatibilityHelper.java:73)
        ... 25 more
Caused by: java.lang.NullPointerException
        at org.apache.maven.plugin.DefaultPluginDescriptorCache$CacheKey.<init>(DefaultPluginDescriptorCache.java:167)
        at org.apache.maven.plugin.DefaultPluginDescriptorCache.createKey(DefaultPluginDescriptorCache.java:62)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:173)
        at org.apache.maven.plugin.DefaultBuildPluginManager.loadPlugin(DefaultBuildPluginManager.java:83)
        ... 30 more

**Comment by rnc** [comment]
Are you able to provide a test case to reproduce the problem?

**Comment by rnc** [comment]
Can you provide the plugin you are executing and the configuration?

**Comment by rnc** [comment]
@hiddusk  Also, further to above, can you try running Maven in debug mode (i.e. with `-X`) and paste the log?

**Comment by rnc** [comment]
I am closing this ; if you can reproduce it with the current codebase, please enter a new ticket
